# Generated by Django 5.0.7 on 2024-09-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_question_section_module_lesson_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='list_of_word_audio',
            field=models.FileField(blank=True, null=True, upload_to='lessons/audio/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='word_audio',
            field=models.FileField(blank=True, null=True, upload_to='lessons/audio/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
