# Generated by Django 5.0.7 on 2024-09-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_lesson_list_of_word_audio_lesson_word_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='task_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='API.taskgroup'),
            preserve_default=False,
        ),
    ]
