# Generated by Django 5.0.7 on 2024-09-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_question_task_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
    ]
