# Generated by Django 5.0.7 on 2024-09-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_taskgroup_image_task_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='list_of_word_audio',
            field=models.FileField(blank=True, null=True, upload_to='lessons/audio/list_of_word/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='word_audio',
            field=models.FileField(blank=True, null=True, upload_to='lessons/audio/word/'),
        ),
    ]
