# Generated by Django 5.0.7 on 2024-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_alter_module_options_module_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='taskgroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskgroup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
