# Generated by Django 5.0.7 on 2024-10-21 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_lesson_list_of_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='API.section'),
        ),
    ]
